# Generated by Django 5.2.1 on 2025-05-11 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("edad", models.IntegerField()),
                ("dni", models.CharField(max_length=8, unique=True)),
                ("sexo", models.CharField(max_length=10)),
                ("direccion", models.TextField()),
                ("historia_clinica", models.CharField(max_length=100)),
                ("tipo_cancer", models.CharField(max_length=100)),
                ("estadio", models.CharField(max_length=50)),
                ("fecha_diagnostico", models.DateField()),
                ("tratamiento_actual", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="UsuarioSalud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("correo", models.EmailField(max_length=254, unique=True)),
                ("contrasena", models.TextField()),
                ("especialidad", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ReporteClinico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("resumen", models.TextField()),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.paciente"
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.usuariosalud",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrediccionAdversa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("riesgo", models.DecimalField(decimal_places=2, max_digits=5)),
                ("tipo_reaccion", models.CharField(max_length=150)),
                ("fecha_prediccion", models.DateTimeField()),
                (
                    "reporte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.reporteclinico",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="paciente",
            name="usuario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.usuariosalud",
            ),
        ),
        migrations.CreateModel(
            name="HistorialInteraccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accion", models.TextField()),
                ("fecha", models.DateTimeField()),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.paciente"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.usuariosalud",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Alerta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nivel_riesgo", models.CharField(max_length=50)),
                ("mensaje", models.TextField()),
                ("fecha_alerta", models.DateTimeField()),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.paciente"
                    ),
                ),
                (
                    "generada_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.usuariosalud",
                    ),
                ),
            ],
        ),
    ]
